source 'https://rubygems.org'

gem 'pry'
gem 'puma'
gem 'rack'
gem 'rack-test'
gem 'rspec'
gem 'rack-cors', require: "rack/cors"
gem 'shotgun'
gem "require_all"
gem "activerecord", "~> 5.2"
gem "sinatra-activerecord"
gem "sqlite3"
gem "faker"